### ISSUE TITLE
Diff contain space and tab

### ISSUE THREAD

**Issue by GreyElec** [mjcrouch/vscode-perforce#111]
at present, the diff view will take space and tab into consideration, which means if you convert the indentation of code from space into the tab, there will be the modification mark all over the code

**Comment by mjcrouch** [comment]
Hi @GreyElec - 

The actual diff algorithm is performed in VS Code itself, we just provide the file contents and they do the diff. You can ignore whitespace in the diff editor (when they're open side-by-side),
you can't ignore whitespace in the gutter decorations though - there's an open issue in the vscode repo - https://github.com/Microsoft/vscode/issues/60594

Thanks

**Comment by GreyElec** [comment]
thanks for the response, it helps a lot.
