### ISSUE TITLE
Bad interaction with Microsoft C++ Extension when viewing diffs

### ISSUE THREAD

**Issue by ryanpholt** [mjcrouch/vscode-perforce#119]
**Describe the bug:**

This is an interaction between the Perforce extension and the Microsoft C++ extension. Whenever I open a diff of a file (by clicking on the file in the SCM view), the C++ extension seems to try to provide Intellisense information for file(s) in the diff (because they are .cpp files). This results in an error notification popup:

"file.cpp?haveRev=4&leftUri=perforce%3A%2Flocal-ssd%2Fryanholt%2Fpath%2Fto%2Ffolder%2Ffile.cpp%3Fcommand%253Dprint%2526p4Args%253D-q%2526rev%253D4%2526haveRev%253D4%234&diffStartFile=file%3A%2F%2F%2Flocal-ssd%2Fryanholt%2Fpath%2Fto%2Ffolder%2Ffile.cpp%3FhaveRev%253D4" not found in "/local-ssd/ryanholt/path/compile_commands.json". 'includePath' from c_cpp_properties.json will be used for this file instead. 

I'm guessing this is because the files opened in the diff view have different paths than the original file.

It doesn't cause me any problems (I guess it means I can't do intellisense code navigation in the diff editor) other than being an annoying popup. The slevesque.perforce extension did not have this issue (it seems to open the diff'd files with the same path as the original?). I added the Perforce output when opening a diff for both extensions below.

**Versions & Details:**
 - Perforce extension: mjcrouch.perforce 4.4.0
 - VSCode version: 1.44.2
 - Operating System: Debian 10
 - Perforce server details (if known):
 - Are you using a multi-root workspace?: Yes

**Additional context**

<details>

```
mjcrouch.perforce

/local-ssd/ryanholt/path/to/folder/: p4 '-c' 'ryanholt.ah-ryanholt-l.local-ssd.ryanholt.blah' 'print' '-q' '/local-ssd/ryanholt/path/to/folder/file.cpp#5'
/local-ssd/ryanholt/path/to/folder/: p4 '-c' 'ryanholt.ah-ryanholt-l.local-ssd.ryanholt.blah' 'opened' '/local-ssd/ryanholt/path/to/folder/file.cpp'

```
```
slevesque.perforce

p4 -c ryanholt.ah-ryanholt-l.local-ssd.ryanholt.blah print -q "/local-ssd/ryanholt/path/to/folder/file.cpp"
p4 -c ryanholt.ah-ryanholt-l.local-ssd.ryanholt.blah opened "/local-ssd/ryanholt/path/to/folder/file.cpp"
p4 -c ryanholt.ah-ryanholt-l.local-ssd.ryanholt.blah opened "/local-ssd/ryanholt/path/to/folder/file.cpp"
```
</details>

**Comment by mjcrouch** [comment]
Thanks, interesting as I use C++ but haven't seen that error pop up. However I assume this it's very much related to #118 - I'm not seeing the error because I only use cpp on remote-SSH and it strips the query params from the URI

I'm going to rework the diffs for workspace files so it doesn't put all the query parameters on the end, it doesn't seem to play nice with a few things in VS Code.

**Comment by ryanpholt** [comment]
Thanks! 

I do not see the error over remote-SSH either. 

I'm guessing you'd also need to configure the C++ extension with a compile_commands.json file to see it over non-remote-SSH as well.

**Comment by mjcrouch** [comment]
Published version 4.4.1 last night that should prevent this - please let me know if it doesn't

**Comment by ryanpholt** [comment]
It seems like it almost fixed it in that the error message is now smaller :). Now I get:

"File.cpp?haveRev=11" not found in "/path/to/folder/compile_commands.json". 'includePath' from c_cpp_properties.json will be used for this file instead.

It seems like it's just the "?haveRev=11" throwing it off now. Any ideas?


This extension is really awesome, by the way. The improved multi root support is fantastic! :)

**Comment by mjcrouch** [comment]
Ah I thought I'd got rid of all the query params, was worried something might sneak in though. Solved my other issue but must have missed one bit, will reopen and fix it..

> This extension is really awesome, by the way. The improved multi root support is fantastic! :)

Thanks :)

**Comment by mjcrouch** [comment]
I see where I've missed it - if you use the left arrow on the file to diff then it should have no params, but if you click the file from the scm provider to do the diff, it adds the haveRev on there

**Comment by allender** [comment]
> This extension is really awesome, by the way. The improved multi root support is fantastic! :)

I agree Matt.   Progress has been great.  Been meaning to help out with things but you've been cranking it out!

**Comment by ryanpholt** [comment]
This is indeed fixed now. Thanks!
