### ISSUE TITLE
Add command to sync a specific revision of the opened file

### ISSUE THREAD

**Issue by ryanpholt** [mjcrouch/vscode-perforce#123]
**Is your feature request related to a problem? Please describe.**

Sometimes I'd like to sync an older/newer revision of the file that I currently have opened.

**Describe the solution you'd like**

Add a perforce command that lets me pick a revision to sync for the current file. Essentially, it would call:

p4 sync /path/to/file#RevisionNum

**Describe alternatives you've considered**

None

**Additional context**

Currently, it seems like there is a perforce sync command that syncs everything (not just the currently opened file).

**Comment by mjcrouch** [comment]
Makes sense - probably two places for this
1 In the status bar menu - "sync revision" (then pick a revision to sync)
2 In the file history quick pick - "sync this revision" - though ideally want to check if the file is mapped in the client view before adding it to this menu, as you can get pretty much anywhere in the depot from this menu
