### ISSUE TITLE
not under client root error when using symlink

### ISSUE THREAD

**Issue by aaronovz1** [mjcrouch/vscode-perforce#127]
I have my P4 workspace directory set to a symlink which points to a directory on mounted drive. This doesn't appear to play nicely with this plugin, and I get errors such as:

```
ERROR: "Path '/media/ssd/dev/myfile.h' is not under client's root '/home/user/dev'
```

I have tried setting the `Perforce: dir` option to `/home/user/dev` and toggling the `Realpath` option but can't get it to work.

Any suggestions? Is this a bug or misconfiguration? I have the same setup working in Sublime

**Comment by mjcrouch** [comment]
Hi - just to check a few things

1. Which dir do you have open in vscode and which is the symlinked dir?
2. Is `/media/ssd/dev/myfile.h` a path underneath a symlinked directory (i.e. not the real path for the file)?
3. If you look at the "perforce log" output, can you give me an example of a command that it runs, and the command you expect it should run instead?

Thanks

**Comment by aaronovz1** [comment]
Hi there,

1. I have the symlink opened in vscode. The symlink is '/home/user/dev' which points to '/media/ssd/dev'. The symlink is what is set in my P4 workspace root.
2. Yes
3. `/home/user/dev/myfile.h: p4 '-u' '****' '-c' '****' '-p' '****' '-P' '****' '-d' '/home/user/dev' 'edit' '/media/ssd/dev/myfile.h'
ERROR: "Path '/media/ssd/dev/myfile.h' is not under client's root '/home/user/dev'`
4. I used the original extension but that didn't work, which is what led me to this newer fork

Thanks

**Comment by mjcrouch** [comment]
Did you try setting perforce.dir to /media/ssd/dev ? 
If you run p4 commands (without the -d) from that directory do they work?

**Comment by aaronovz1** [comment]
No luck with that.

It seems that however it gets the path for the file to checkout needs to use the symlink and not the real path. For example the command that works when run manually is:

`p4 '-u' '****' '-c' '****' '-p' '****' '-P' '****' '-d' '/home/user/dev' 'edit' '/home/user/dev/myfile.h'`

**Comment by mjcrouch** [comment]
ok, if it all works from the symlink dir,  try

set perforce.activationMode to always
remove the perforce.dir and perforce.realPath settings

restart

**Comment by aaronovz1** [comment]
I thought I had tried that before posting this but it looks like it is working :) Maybe I forgot to save the settings last time. Thanks.

No actual issue, just misconfiguration - closing
