### ISSUE TITLE
action to edit changelist description

### ISSUE THREAD

**Issue by tstack** [mjcrouch/vscode-perforce#143]
It would be nice to be able to edit a changelist directly in vscode (i.e. the `p4 change <CLN>` command).  Is that something that could be added to this extension?

**Comment by mjcrouch** [comment]
Hi - if you mean what I think you mean, I just added that in the last update yesterday (4.7.0)

You can right click on a changelist and choose "Edit changelist spec" to open it in the editor, or if you want to edit another changelist not shown, from the changelist quick pick (which you can get to with "go to changelist" or the changelist search)

**Comment by tstack** [comment]
Ah, yep, that's what I was looking for, thanks!
