### ISSUE TITLE
Start changelist descriptions collapsed

### ISSUE THREAD

**Issue by allender** [mjcrouch/vscode-perforce#145]
**Is your feature request related to a problem? Please describe.**
When there are potentially hundreds of files per changelist, I think that it could be beneficial to start the changelist descriptions all collapsed so that it is easier to find changelists.  (One potential addition would be to add a "collapse all"/"open all" kind of context menu in that window as well.

Would be happy to implement if you find that this might be useful or have ideas on how to particularly implement something.

**Comment by mjcrouch** [comment]
Agree that this could be useful, however as far as I can tell there's nothing in the vscode API for us to control the collapsed / expanded state of changelists in the SCM view. This would probably need to be raised in the vscode repo, might be more of a general feature for vs code

**Comment by allender** [comment]
Booo!  ok.  Thanks for checking into that.  I'll live with it and think about posting there.  Thanks Matt.
