### ISSUE TITLE
vscode-perforce thinks folder is not client because of case-sensitivity

### ISSUE THREAD

**Issue by glutinous** [mjcrouch/vscode-perforce#164]
This is probably Windows-only.

My workspace has the root set to c:\depot.

On Windows, it is c:\Depot.

So vscode-perforce fails to work because it thinks c:\Depot is not mapped. Regular p4 commands from cmd.exe work perfectly fine. It looks like vscode-perforce is not working because of the difference in case.

As a workaround, I renamed c:\Depot to c:\depot and everything works again.

**Comment by mjcrouch** [comment]
thanks - I have wondered about this kind of thing but haven't got round to testing it - will need to look in to the 'right' thing to do.

Possibly the right thing is for us to check whether the server is case insensitive and then relax that check - not 100% sure if that accounts for all the cases, and whether there are any other parts of the code that would break once it does activate.
