### ISSUE TITLE
Ability to perforce sync current (VS Code) workspace

### ISSUE THREAD

**Issue by maciejmatczak** [mjcrouch/vscode-perforce#169]
**Is your feature request related to a problem? Please describe.**
It seems I cannot sync only opened folder. Plugin uses generic expression which syncs whole P4 workspace.

**Describe the solution you'd like**
Current _Perforce: Sync_ should use `p4 sync ./...` (when used within the VS Code workspace directory) or explicit VS Code workspace path + `./...`.

Right now `p4 sync` synchronizes whole P4 workspace, not folder I have opened. 

**Describe alternatives you've considered**
New option (next to current _Perforce: Sync_) - _Perforce: Sync current workspace_.

**Additional context**
I am more into "sync only current workspace" as a default behavior. VS Code P4 plugin should be only able to deal with currently opened folder, it feels more natural.

**Comment by mjcrouch** [comment]
Was just thinking about this on friday when I accidentally synced a huge workspace when I only had a folder open

There is one thing that I added a while ago - you can right click on a folder in the explorer and choose to sync that folder - this includes the top level folder- So if you right click on the whitespace at the bottom of the explorer. This is not very obvious though, and can be hard to get to for a big workspace

I think the 'sync current workspace' is probably reasonable 

there are some edge cases like multiple perforce clients, and perforce clients *under* the workspace root (not at the same level) - but then the existing context menu could work for those. Maybe we should hide the option from the context menu if the selected client doesn't contain the workspace folder.

**Comment by maciejmatczak** [comment]
In my case I have one client, many tools under one depot. So I am opening a VS Code on `/path/to_my_p4ws/depot/tools/toolA`, which is mapped from `//depot/tools/toolA`.

So having a VS Code opened in `/path/to_my_p4ws/depot/tools/toolA` and syncing, in my opinion, shouldn't do anything else then exactly: `p4 sync /path/to_my_p4ws/depot/tools/toolA/...`. And this does follows what plugin does for changelist view - the one outside the currently opened folder are not shown at all, right?

Plugin settings for syncing behavior would be nice, it would solve my problems once and globally (sth like `Use workspace directory when syncing`).

**Comment by mjcrouch** [comment]
> And this does follows what plugin does for changelist view - the one outside the currently opened folder are not shown at all, right?

It's an option - the default is actually to show all changelists for that perforce client, even if they only contain files in different places outside of the vs code workspace.

(Also as mentioned in my previous if you open a file from another perforce client then you may see an additional scm provider (aka changelist view) for that perforce client depending on how your environment is set up, I think that can be handled e as we can look at the context of how the command was invoked and see that this is the case.)

I definitely think yours is probably the more common case, but need to think about the best way to handle everything and what the best name / values / behaviours for a setting might be - I don't have a lot of time right now but will hopefully be able to get back to it soon

**Comment by maciejmatczak** [comment]
`perforce.hideNonWorkspaceFiles` - of course it is! Excuse me this oversight, I set it once (after being confused by default behavior ;) ) and honestly forgot. Thanks for pointing it out.

Sounds good to me Matt, I will use "right click on a blank" workaround up to then. Thanks.
