### ISSUE TITLE
Stuck with "Performing one-time registration of perforce commands" message

### ISSUE THREAD

**Issue by annag-altair** [mjcrouch/vscode-perforce#189]
**Describe the bug:**
After installing the extension and configuring P4 the output is stuck on "Performing one-time registration of perforce commands
" and nothing happens

**Expected behavior:**
The extension should work

**Versions & Details:**
 - Perforce extension:  4.14.0
 - VSCode version: 1.50.1
 - Operating System: WIN10
 - Perforce server details (if known): perforce:1666
 - Are you using a multi-root workspace?: No

**Additional context**

<details>

```
Performing one-time registration of perforce commands
```

</details>

**Comment by mjcrouch** [comment]
Hi, Seems strange! Can you check the javascript console for any exceptions / errors?

You can run "Developer: Toggle Developer Tools" to see the console

**Comment by annag-altair** [comment]
I have those errors:

![image](https://user-images.githubusercontent.com/55234286/97778312-2aee7800-1b7f-11eb-8df8-8bf2eebbff1e.png)

**Comment by mjcrouch** [comment]
Do you have another perforce extension installed? It looks like something else has already registered a command with the same name.

**Comment by annag-altair** [comment]
I checked and found another extension installed. I uninstalled it. Now it is working. Thanks a lot!
