### ISSUE TITLE
Folder specific setup script before extension load

### ISSUE THREAD

**Issue by natebot13** [mjcrouch/vscode-perforce#191]
I have multiple clients/workspaces with a path structure like this:
nathan/work1
nathan/work2
etc.
At my work, we have to run a bash script that sets up our bash environment to use the tools under the specific workspace we're working on. This does a plethora of things, but mainly sets up a bunch of environment variables, namely some perforce vars for the specific workspace we're working under.

I've found that this work flow doesn't really work with this extension, as I need some way to run the setup script before this extension tries to execute any perforce commands.

I've tried just having the setup script run in my .bashrc, and this technically works, but only works for one workspace at a time. If I want to work on another workspace, I have to modify the bashrc to use the correct folder's script, and then I can open vscode in that folder, which loads everything correctly.

I've also tried adding a "runOn": "folderOpen" task to tasks.json, but this doesn't seem to setup the environment for vs code itself, and instead just opens a new terminal and runs the script there.

I realize this might not actually be perforce extension specific, but I haven't been able to find a proper solution, so any help would be appreciated!

**Comment by mjcrouch** [comment]
For this kind of scenario I would normally recommend you use P4CONFIG. i.e. in your .bashrc set P4CONFIG=.p4config, then create .p4config files at the root of each folder with the right perforce variables. There's an example in the readme.

This should work if you don't have other non-perforce things as part of your environment set-up.

> I've also tried adding a "runOn": "folderOpen" task to tasks.json, but this doesn't seem to setup the environment for vs code itself, and instead just opens a new terminal and runs the script there.

Yes - I don't think a task is able to update the actual vs code environment - each task / shell has its own env

**Comment by mjcrouch** [comment]
closing this off as I don't think there's much we can do here beyond .p4config files as above
