### ISSUE TITLE
Automatic operations not working

### ISSUE THREAD

**Issue by terids** [mjcrouch/vscode-perforce#199]
**Describe the bug:**
I've added perforce.editOnFileSave and perforce.addOnFileModified in my settings file, but I only ever get a read only file.

**Expected behavior:**
The file(s) would be checked out in p4 and added to the default changelist

**To Reproduce:**
Add these settings to your settings.json, and edit a file that lives in the perforce repo

**Versions & Details:**
 - Perforce extension: 4.14.0
 - VSCode version: 1.52.1
 - Operating System: Windows 10
 - Perforce server details (if known): Latest version
 - Are you using a multi-root workspace?: No

**Additional context**

<details>

```
c:\wkspaces\Unity\Dusk\Assets\Scripts: p4.exe 'opened' 'c:\wkspaces\Unity\Dusk\Assets\Scripts\Health.cs'
c:\wkspaces\Unity\Dusk\Assets\Scripts: p4.exe 'have' 'c:\wkspaces\Unity\Dusk\Assets\Scripts\Health.cs'
c:\wkspaces\Unity\Dusk\Assets\Scripts: p4.exe 'print' '-q' 'c:\wkspaces\Unity\Dusk\Assets\Scripts\Health.cs#have'
c:\wkspaces\Unity\Dusk\Assets\Scripts: p4.exe 'print' '-q' 'c:\wkspaces\Unity\Dusk\Assets\Scripts\Health.cs#have'
```

The above snippet is me opening the file, making an edit, hitting save, with both editOnFileSave and editOnFileModified enabled.

</details>

**Comment by mjcrouch** [comment]
Hi - thanks for reporting - I haven't been able to reproduce this.
IIRC these settings do require a restart to register properly - Assuming you have tried restarting vs code after enabling the setting?

If so, could you open the dev console (developer: Toggle developer tools) and check if there are any javascript errors in the console when you modify / save a file?

**Comment by terids** [comment]
Yep i've restarted VSCode, and my computer.

![screenshot1603](https://user-images.githubusercontent.com/10546876/104840493-07a1b200-58be-11eb-898c-416a82ba6360.png)

I think this is the only relevant error, there is another at the top because I don't have a .vscode forder

![screenshot1604](https://user-images.githubusercontent.com/10546876/104840847-20aa6300-58be-11eb-8e0b-7cad9675e9f5.png)

**Comment by terids** [comment]
I figured out it wasn't reading the correct workspace name, I've set it up with a .p4config instead of reading the registry. Sorry for the inconvenince!
