### ISSUE TITLE
Source control icon shows wrong open file amount

### ISSUE THREAD

**Issue by ulfwinberg** [mjcrouch/vscode-perforce#205]
**Describe the bug:**

The control icon does not reflect the actual amount of files open (in this example shows 16, but should be 1):
![image](https://user-images.githubusercontent.com/79083248/108819533-3f85ce80-75bb-11eb-9938-a0ecabee0146.png)

It seems to keep the amount from previous changelists that were submitted since if you try to move a file to a new changelist, older already submitted changelists appear in the drop-down list.

**Expected behavior:**

Only the currently open files should be counted

**To Reproduce:**

Submit a changelist, and see that the file amount is wrong.

**Versions & Details:**
 - Perforce extension:  4.15.0
 - VSCode version: 1.53.2
 - Operating System: Windows_NT x64 10.0.17763
 - Perforce server details (if known): P4D/LINUX26X86_64/2018.2/1779952 (2019/04/02)
 - Are you using a multi-root workspace?: Yes

**Additional context**

<details>

Perforce output from pressing refresh:
```
s:\perforce\ulf_lundcs7_A12_tests_libdev_4193: p4.exe 'login' '-s'
s:\perforce\ulf_lundcs7_A12_tests_libdev_4193: p4.exe 'login' '-s'
s:\perforce\ulf_lundcs7_A12_tests_libdev_4193: p4.exe 'changes' '-l' '-c' 'ulf_lundcs7_A12_tests_libdev_4193' '-s' 'pending'
s:\perforce\ulf_lundcs7_A12_tests_libdev_4193: p4.exe 'describe' '-S' '-s' '1030808'
s:\perforce\ulf_lundcs7_A12_tests_libdev_4193: p4.exe 'opened'
s:\perforce\ulf_lundcs7_A12_tests_libdev_4193: p4.exe 'fstat' '-Or' '//haps/A12_tests_libdev/aFPGA/general/doc/A12_aFPGA_general_Signal_Mapping.xlsx'
```
</details>

Thanks for an otherwise great extension! Very happy that it got picked up, and made a lot better :D

**Comment by mjcrouch** [comment]
Thanks - looks similar to something mentioned in #201 but I couldn't work out how to repro - this works though - basically submitting a changelist doesn't remove it properly.

I think I can see where the error is - just forgot to remove the changelist from a collection when it's not needed any more - will get it fixed :)

**Comment by ulfwinberg** [comment]
Great, thanks for super fast response!
