### ISSUE TITLE
Unable to attach a Perforce job that contains hyphens

### ISSUE THREAD

**Issue by isc-kiyer** [mjcrouch/vscode-perforce#208]
**Description:**
When I try to right click a changelist and attach a job, I get an error that the job name must only contain letters and numbers. However, this is not a restriction applied by perforce itself. I have Perforce jobs that contain hyphens and P4V lets me attach those.

**Expected behavior:**
Should allow me to add the job.

**To Reproduce:**
Right click any changelist and select "Attach job"
Try typing a job name which contains hyphens. You should see the following error:
![Unable_to_add_job](https://user-images.githubusercontent.com/75783557/117371204-1d76c980-aee5-11eb-9dab-91112ea770d7.png)

**Versions & Details:**
 - Perforce extension: 4.15.1
 - VSCode version: 1.54.3
 - Operating System: Mac OS Big Sur v11.2.2
 - Perforce server details (if known): 2019.2
 - Are you using a multi-root workspace?: No

**Comment by mjcrouch** [comment]
Thanks for raising, I'll look to address this soon :). Interestingly it looks like I've added two different functions for entering a job id and only one of them does this validation :D

**Comment by isc-kiyer** [comment]
Thanks for the quick response!
