### ISSUE TITLE
Use VSCode as the editor for p4 resolve on remote workspace.

### ISSUE THREAD

**Issue by Thomasyse** [mjcrouch/vscode-perforce#214]
**Is your feature request related to a problem? Please describe.**
By now there is an option to override the P4EDITOR in the setting to set VSCode as the editor for p4 resolve. But it doesn't support Remote-SSH.

**Describe the solution you'd like**
Just the same experience as the one for local workspace.

**Comment by mjcrouch** [comment]
Hi - In the extension, we're setting the P4EDITOR environment variable on the remote shell and then p4 runs the command. The extension doesn't have any control over what vs code does with that command - so it would require core vs code to support opening a file in the remote-SSH session from a command run on the remote server. I don't think there's anything we can change in the extension.

From a bit of googling, It's quite possible that vs code does already support this if you use the right set of args or a script of some kind, unfortunately I don't have a remote SSH server to connect to anymore, so not able to test this myself.
