### ISSUE TITLE
Cannot read "P4CONFIG", not set in environment. Not clear on how.

### ISSUE THREAD

**Issue by SilverGekko** [mjcrouch/vscode-perforce#217]
**Describe the bug:**
I am unable to rely on the .p4config file in my workspace root. The extension reports that it finds the file, but P4CONFIG is "not set in my environment" and it will not use settings found inside my p4config file. When I manually set P4PORT, P4USER and P4CLIENT in settings.json, it works.

**Expected behavior:**
I expect the extension to tell me how to set up my "environment" properly so I do not have to rely on manually setting perforce.user, perforce.port, and perforce.client as I wish to use vscode on multiple workspaces.

**To Reproduce:**
I am running vscode on windows. I use remote-ssh to a red hat 7.8 machine that is running perforce and has the workspace checked out. Leave perforce.user, perforce.port, and perforce.client blank. The log below is generated, complaining about improperly set P4CONFIG. I have P4CONFIG set in my cshrc that runs in the terminal profile I have set up for VS code. When I manually set these perforce variable to the values found in the p4config command, it works and I can view changelists and diffs from perforce in VS code. Running "p4 set" on the server machine properly shows the p4config variable being set with my p4config file.

**Versions & Details:**
 - Perforce extension: ms-vscode-remote.remote-ssh version 0.65.7
 - Perforce extension: mjcrouch.perforce version 4.15.2
 - VSCode version: 1.58.1
 - Operating System: Windows 10 Enterprise Build 18363
 - Operating System: Red Hat Enterprise 7.8
 - Perforce server details (if known):
 - Are you using a multi-root workspace?: No

**Additional context**

<details>

```
Performing one-time registration of perforce commands
==============================
Workspace folders changed. Starting initialisation.

Workspaces were added
> file:///path/to/dir/workspace/: Trying to initialise SCM Providers in this workspace.
	Note: the following overrides apply in this workspace:
		perforce.port: 	(will not override)
		perforce.user: 	(will not override)
		perforce.client: 	(will not override)
		perforce.dir: none	(will not override)
	Explicit overrides may prevent auto-detection of other perforce client workspaces
Looking for a client root using the workspace root directory
file:///path/to/dir/workspace/: /path/to/p4 'info'
ERROR: "Perforce client error:\n\tConnect to server failed; check $P4PORT.\n\tTCP connect to perforce:1666 failed.\n\tName or service not known\n"
ERROR: "Perforce client error:\n\tConnect to server failed; check $P4PORT.\n\tTCP connect to perforce:1666 failed.\n\tName or service not known\n"
>file:///path/to/dir/workspace/: NO CLIENT ROOT FOUND in workspace root directory
> file:///path/to/dir/workspace/: Looking for perforce config files
file:///path/to/dir/workspace/: /path/to/p4 'set' '-q'
>file:///path/to/dir/workspace/: Did NOT find a valid P4CONFIG setting.
!!! IMPORTANT !!!
Previously, if no P4CONFIG setting was found, the extension would look for files name .p4config and parse them.
This is no longer the case. If you use p4config files, Please set your P4CONFIG setting and restart,
Either via environment variables or p4 set, e.g.:
		p4 set P4CONFIG=.p4config
!!! IMPORTANT !!!
```

</details>

**Comment by mjcrouch** [comment]
Thanks for raising & including detail - I'm a bit stumped atm.

- It sounds like whatever shell is actually executing the perforce commands hasn't picked up on your environment
- Since you have it in your cshrc with would imply it's using a different shell or settings for the automation shell compared to the normal integrated terminal
- Have you overriden any shell related settings, e.g. `terminal.integrated.automationShell.linux`?
- I'm assuming that your P4CONFIG setting is not ".p4config" (otherwise we would have found a .p4config file in your workspace and logged another warning about that) - though this shouldn't affect any actual behaviour so probably isn't relevant

**Comment by SilverGekko** [comment]
My p4config is "p4config" with no dot prefix. I do agree this isn't relevant because the error log states that method of detection is deprecated and I should rely on the new P4CONFIG environment var to detect the perforce config.

I have `"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",` on my windows settings, and no terminal settings overwritten on my remote:
![image](https://user-images.githubusercontent.com/7212912/127910829-dc19ba43-056d-4377-8496-609f45db3afe.png)

I tried setting up the P4CONFIG env var in a custom environment setting here:

![image](https://user-images.githubusercontent.com/7212912/127911478-87ceb79e-f19b-437b-96a7-164e9411d15f.png)

But I get the same log generated in the first post.

(The shellArgs do work though)
![image](https://user-images.githubusercontent.com/7212912/127911641-89e57832-9ba3-4c5d-ada5-6eb851a995ed.png)

Is there another VSCode setting I can try to see what shell the perforce commands are being run in?

**Comment by mjcrouch** [comment]
Not entirely sure but would be interesting to see what it would output if you set up a custom task to run a p4 command or echo the env vars. I *think* that should use the same shell

 Did you try that command with the env vars in the automation shell setting instead of the integrated shell?

**Comment by SilverGekko** [comment]
I did not try it in the automation shell; I think you're onto something.

Setting up a custom vscode task just to run 'env' shows no perforce env vars, and a task set to run 'p4 info' expected errors because it can't find p4 info.

It is my understanding that the automation shell tasks are run in explicitly ignore user args. What would be the best way to ensure that vscode-perforce runs in a shell with these args? A custom task maybe?
