### ISSUE TITLE
Extension stuck "Checking file status" 

### ISSUE THREAD

**Issue by jsguay-haven** [mjcrouch/vscode-perforce#234]
**Describe the bug:**
Once in a while (it's happened twice today so far) the extension seems to get into a state where it's spinning on "Checking file status" forever. When it's in that state, it does not do anything else, like check out files I edit in vscode. I have tried doing "Log out of Perforce" and "Log into Perforce" but it seems like they don't do anything either.

The only workaround I have found is to disable and reenable the extension, but that forces a reload of vscode which leads to rust-analyzer re-indexing all our code, so vscode is sluggish for a minute or two after that. It's faster than closing vscode and restarting it, but not by much.

**Expected behavior:**
The extension should not get into an unresponsive state.

**To Reproduce:**
I have not yet found something I do that causes this, it seems to happen at random. I know that's not very helpful... I'll see if I can spot a pattern and report here if I do.

**Versions & Details:**
 - Perforce extension: v4.15.2
 - VSCode version: 1.69.2
 - Operating System: Windows 10
 - Perforce server details (if known): ?
 - Are you using a multi-root workspace?: No

**Additional context**

<details>

Sorry I can't give you the log but it shows that the last several commands are a series of p4 print and p4 opened commands.

</details>

**Comment by mjcrouch** [comment]
Hi,

I have a theory here about what's happening. As I recall it was much more likely to occur in the old extension that this one is based on -
There is a setting called `perforce.bottleneck.maxConcurrent`  - the idea is to ensure we never have more than x commands ongoing concurrently, to avoid 'spamming' the perforce server. This was implemented in the original extension but it was heavyweight and also buggy - the extension would become non-responsive because it didn't always tidy up properly, so it thought there were more commands running than there actually were and once it reached the limit, all new commands were queued and nothing worked any more. Anyway, I reimplemented it and haven't knowingly seen that problem since.

My theory is that for whatever reason, you have, or we think you have, more than the limit of perforce commands running concurrently. Perhaps your commands get 'stuck' somehow and the shell never gets a response, perhaps there's a bug in the extension or even vscode api where we're not marking a command complete (I think [this should really be in a finally block](https://github.com/mjcrouch/vscode-perforce/blob/master/src/CommandLimiter.ts#L111), then we could rule that out).

So the default bottleneck setting is 10, and as soon as you have 10 'stuck' commands the extension will stop being responsive. If this is the case, you will see in the perforce log that when you try to run any perforce commands, it won't output anything to the perforce log.

Another way to verify this is to enable the setting `perforce.debugModeActive`, then restart vs code. With this setting enabled, open the developer tools (Developer: Toggle developer tools) and watch the console log - when we reach the bottlneck, you will start seeing console logs with "Command Limiter: .... ENQUEUE ..." to show that we're queuing commands instead of running them.

If this is the case, a short term fix might be just to increase the maxConcurrent setting - but we should ideally understand the underlying cause!

**Comment by jsguay-haven** [comment]
Hi Matt,

Thanks a lot for this, I was worried when I posted the issue that the reply would be "if it seems random and you don't have specific repro steps, then we can't do anything" ...

I have enabled `perforce.debugModeActive` and restarted vscode. I'll keep an eye on the developer tools console and see if I get the results you're thinking I'll get. For now all I'm seeing are "Command Limiter: ... EXECUTING" and "COMPLETED" messages. I'll keep you posted (though I won't do much coding over the weekend, but early next week hopefully I'll be able to report back).

Thanks again!

**Comment by jsguay-haven** [comment]
What is the number next to "R" in the Command Limiter messages? What I am seeing is that some commands seem to generate warnings and errors ("rejected promise not handled within 1 second: TypeError: e.replace is not a function", full stack trace below) and then the "R" number never goes back down to 0. Each time there's an error like that, one "R" seems to stay stuck. It's now at 8. I'm guessing once it gets to 10 stuck, then it will start enqueueing commands and the extension will seem stuck.

Stack trace for the errors I'm seeing:
```
[Extension Host] stack trace: TypeError: e.replace is not a function
	at C:\Users\jsguay_havenstudios\scoop\persist\vscode\data\extensions\mjcrouch.perforce-4.15.2\dist\extension.js:1:64039
	at Array.map (<anonymous>)
	at C:\Users\jsguay_havenstudios\scoop\persist\vscode\data\extensions\mjcrouch.perforce-4.15.2\dist\extension.js:1:64026
	at C:\Users\jsguay_havenstudios\scoop\persist\vscode\data\extensions\mjcrouch.perforce-4.15.2\dist\extension.js:1:64065
	at C:\Users\jsguay_havenstudios\scoop\persist\vscode\data\extensions\mjcrouch.perforce-4.15.2\dist\extension.js:1:64189
	at C:\Users\jsguay_havenstudios\scoop\persist\vscode\data\extensions\mjcrouch.perforce-4.15.2\dist\extension.js:1:64979
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by jsguay-haven** [comment]
You were right. Console log for the past few seconds:

```
[Extension Host] Command Limiter: R: 9 Q: 0 :  EXECUTING <JOB_ID:100:opened>
console.ts:137 [Extension Host] Command Limiter: R: 10 Q: 0 :  COMPLETED <JOB_ID:100:opened>
console.ts:137 [Extension Host] Command Limiter: R: 9 Q: 0 :  EXECUTING <JOB_ID:101:print>
console.ts:137 [Extension Host] Command Limiter: R: 10 Q: 0 :  COMPLETED <JOB_ID:101:print>
console.ts:137 [Extension Host] Command Limiter: R: 9 Q: 0 :  EXECUTING <JOB_ID:102:opened>
console.ts:137 [Extension Host] Command Limiter: R: 10 Q: 0 :  COMPLETED <JOB_ID:102:opened>
console.ts:137 [Extension Host] Command Limiter: R: 9 Q: 0 :  EXECUTING <JOB_ID:103:print>
console.ts:137 [Extension Host] Command Limiter: R: 10 Q: 0 :  COMPLETED <JOB_ID:103:print>
console.ts:137 [Extension Host] Command Limiter: R: 9 Q: 0 :  EXECUTING <JOB_ID:104:opened>
console.ts:137 [Extension Host] Command Limiter: R: 10 Q: 0 :  COMPLETED <JOB_ID:104:opened>
console.ts:137 [Extension Host] Command Limiter: R: 9 Q: 0 :  EXECUTING <JOB_ID:105:print>
console.ts:137 [Extension Host] Command Limiter: R: 10 Q: 0 :  COMPLETED <JOB_ID:105:print>
console.ts:137 [Extension Host] Command Limiter: R: 9 Q: 0 :  EXECUTING <JOB_ID:106:opened>
console.ts:137 [Extension Host] Command Limiter: R: 10 Q: 0 :  COMPLETED <JOB_ID:106:opened>
console.ts:137 [Extension Host] Command Limiter: R: 9 Q: 0 :  EXECUTING <JOB_ID:107:opened>
console.ts:137 [Extension Host] rejected promise not handled within 1 second: TypeError: e.replace is not a function
D @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:455
_invokeHandler @ rpcProtocol.ts:440
_receiveRequest @ rpcProtocol.ts:370
_receiveOneMessage @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:572
deliver @ event.ts:774
fire @ event.ts:735
fire @ ipc.net.ts:638
_receiveMessage @ ipc.net.ts:959
(anonymous) @ ipc.net.ts:832
invoke @ event.ts:572
deliver @ event.ts:774
fire @ event.ts:735
acceptChunk @ ipc.net.ts:382
(anonymous) @ ipc.net.ts:338
O @ ipc.net.ts:60
emit @ node:events:390
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:199
console.ts:137 [Extension Host] stack trace: TypeError: e.replace is not a function
	at C:\Users\jsguay_havenstudios\scoop\persist\vscode\data\extensions\mjcrouch.perforce-4.15.2\dist\extension.js:1:64039
	at Array.map (<anonymous>)
	at C:\Users\jsguay_havenstudios\scoop\persist\vscode\data\extensions\mjcrouch.perforce-4.15.2\dist\extension.js:1:64026
	at C:\Users\jsguay_havenstudios\scoop\persist\vscode\data\extensions\mjcrouch.perforce-4.15.2\dist\extension.js:1:64065
	at C:\Users\jsguay_havenstudios\scoop\persist\vscode\data\extensions\mjcrouch.perforce-4.15.2\dist\extension.js:1:64189
	at C:\Users\jsguay_havenstudios\scoop\persist\vscode\data\extensions\mjcrouch.perforce-4.15.2\dist\extension.js:1:64979
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
D @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:455
_invokeHandler @ rpcProtocol.ts:440
_receiveRequest @ rpcProtocol.ts:370
_receiveOneMessage @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:572
deliver @ event.ts:774
fire @ event.ts:735
fire @ ipc.net.ts:638
_receiveMessage @ ipc.net.ts:959
(anonymous) @ ipc.net.ts:832
invoke @ event.ts:572
deliver @ event.ts:774
fire @ event.ts:735
acceptChunk @ ipc.net.ts:382
(anonymous) @ ipc.net.ts:338
O @ ipc.net.ts:60
emit @ node:events:390
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:199
mainThreadExtensionService.ts:79 [[object Object]]e.replace is not a function
$onExtensionRuntimeError @ mainThreadExtensionService.ts:79
_doInvokeHandler @ rpcProtocol.ts:455
_invokeHandler @ rpcProtocol.ts:440
_receiveRequest @ rpcProtocol.ts:370
_receiveOneMessage @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:572
deliver @ event.ts:774
fire @ event.ts:735
fire @ ipc.net.ts:638
_receiveMessage @ ipc.net.ts:959
(anonymous) @ ipc.net.ts:832
invoke @ event.ts:572
deliver @ event.ts:774
fire @ event.ts:735
acceptChunk @ ipc.net.ts:382
(anonymous) @ ipc.net.ts:338
O @ ipc.net.ts:60
emit @ node:events:390
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:199
mainThreadExtensionService.ts:80 TypeError: e.replace is not a function
	at C:\Users\jsguay_havenstudios\scoop\persist\vscode\data\extensions\mjcrouch.perforce-4.15.2\dist\extension.js:1:64039
	at Array.map (<anonymous>)
	at C:\Users\jsguay_havenstudios\scoop\persist\vscode\data\extensions\mjcrouch.perforce-4.15.2\dist\extension.js:1:64026
	at C:\Users\jsguay_havenstudios\scoop\persist\vscode\data\extensions\mjcrouch.perforce-4.15.2\dist\extension.js:1:64065
	at C:\Users\jsguay_havenstudios\scoop\persist\vscode\data\extensions\mjcrouch.perforce-4.15.2\dist\extension.js:1:64189
	at C:\Users\jsguay_havenstudios\scoop\persist\vscode\data\extensions\mjcrouch.perforce-4.15.2\dist\extension.js:1:64979
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:80
_doInvokeHandler @ rpcProtocol.ts:455
_invokeHandler @ rpcProtocol.ts:440
_receiveRequest @ rpcProtocol.ts:370
_receiveOneMessage @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:572
deliver @ event.ts:774
fire @ event.ts:735
fire @ ipc.net.ts:638
_receiveMessage @ ipc.net.ts:959
(anonymous) @ ipc.net.ts:832
invoke @ event.ts:572
deliver @ event.ts:774
fire @ event.ts:735
acceptChunk @ ipc.net.ts:382
(anonymous) @ ipc.net.ts:338
O @ ipc.net.ts:60
emit @ node:events:390
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:199
console.ts:137 [Extension Host] Command Limiter: R: 10 Q: 0 :  ENQUEUE <JOB_ID:108:opened>
console.ts:137 [Extension Host] Command Limiter: R: 10 Q: 1 :  ENQUEUE <JOB_ID:109:print>
console.ts:137 [Extension Host] Command Limiter: R: 10 Q: 2 :  ENQUEUE <JOB_ID:110:opened>
```

It looks like the errors occur when I do a "find in files" -- I have the setting `"search.mode": "reuseEditor",` in my config, and it looks like the extension is trying to check if the editor tab in which the search occurs is in perforce? This is not a real file, so it fails, and I suspect that's what leads to those errors and stuck commands. Does that seem like it could be the cause?

**Comment by mjcrouch** [comment]
Thanks for the details, I was able to repro it just by choosing "open in editor" when searching all files.

It was a combination of a couple of problems
 - The search editor has a different URI to normal windows, with an empty fsPath - we weren't handing it properly and it produced an exception when trying to log the command to the status window
 - The async exception wasn't being handled at-all, so the command was never marked as complete

I have coded a fix for it, but I need to fix the CI builds since it's been so long since I last pushed a release, which I'll try to have a look into tomorrow (no guarantees!)

**Comment by jsguay-haven** [comment]
That's awesome, thanks a lot. Looking forward to the release with the fix, but yeah, take the time it takes to do it right :)

**Comment by jsguay-haven** [comment]
I can confirm after vscode updated the extension to 4.15.3 and restarted, I no longer get errors in the console log when doing find in files. I will use it for a while and see but I am pretty sure the issue is fixed. Thanks a lot for the quick turnaround!
