### ISSUE TITLE
Quick diff randomly fails on some files

### ISSUE THREAD

**Issue by BluTree** [mjcrouch/vscode-perforce#253]
**Describe the bug:**

Sometimes, when opening a file and modifying it, the quick diff margin doesn't appear at all. Reopening the file doesn't fix the problem, I must restart VS Code to see it.

**Expected behavior:**

Quick diff working as intended.

**To Reproduce:**

This can appear very randomly, but I noticed the bug quite often on a short period of time.
This appeared most of the time on big files (250+ lines)

**Versions & Details:**
 - Perforce extension: 4.15.7
 - VSCode version: 1.76.1
 - Operating System: Windows 10 19044.2604
 - Perforce server details (if known):
 - Are you using a multi-root workspace?: No

**Additional context**
When trying to add a small print on the function registered for quick diff on your code, I noticed the function wasn't called when quick diff wasn't appearing. But I don't have enough knowledge about VS Code extension to know if this problem comes from your extension or VS Code directly.

**Comment by mjcrouch** [comment]
Hi,

> When trying to add a small print on the function registered for quick diff on your code, I noticed the function wasn't called when quick diff wasn't appearing.

Thanks for this, that does make me suspect it could be a vs code problem since it's responsible for requesting the original version

- has it been happening for a long time (i.e. not just in the last week or so - I had to touch the quick diff provider in 4.15.7 to work around a vs code issue)?
- do you know if you've previously opened the files in the same editor instance before it happens, or is it the first time you open it?

**Comment by BluTree** [comment]
> has it been happening for a long time

I noticed the problem only yesterday, I use the extension since about a year and I didn't notice this.

> do you know if you've previously opened the files in the same editor instance before it happens, or is it the first time you open it?

This happens the first time I open it. If the quick diff worked at the first opening it will always work, and if not it will never work until I restart completely VS Code.

**Comment by mjcrouch** [comment]
I haven't tried to reproduce it yet, but there are a couple of issues from a quick search in vs code repo that could possibly be related [#173763](https://github.com/microsoft/vscode/issues/173763) , [#177090](https://github.com/microsoft/vscode/issues/177090)

**Comment by BluTree** [comment]
VS Code has updated to 1.76.2 by fixing an issue corresponding to my problem : https://github.com/microsoft/vscode/issues/176738
It seemed to be a problem from VS Code itself.
I close this issue as it seems to be fixed for me, from the few tests I did.
Thanks for the answers anyway !
