### ISSUE TITLE
Why are shelved files being shown in separate subfolders?

### ISSUE THREAD

**Issue by dmiller-bgc** [mjcrouch/vscode-perforce#254]
**Describe the bug:**
When a given file is edited with a path of, say, `~/UK/GTS/Software/cfg/hftz/alpha_repo_allocator.ini` is shelved, the shelved file will appear in a separate "subdirectory" of the changelist.

This is an annoyance which doesn't prevent me from working.

For some reason I cannot paste a screen snip here, so I will approximate what I see in text:

```
V  #4: The changelist description
  V  GTS / Software / cfg / hftz
    = alpha_repo_allocator.ini           [SE]           (NOTE: this item is a shelved file and appears grayed)
  V  UK / GTS / Software / cfg / hftz
    = alpha_repo_allocator.ini            [E]           (NOTE: this item is the edited file)
```

(Please note that when I hover the mouse over the nested "directory" containing the *shelved* item, a tooltip pops up showing the directory, "`~/UK/GTS/Software/cfg/hftz`" and when I hover over the shelved item itself, I get "`/GTS/Software/cfg/hftz/alpha_repo_allocator.ini`". 

Conversely, when I hover over the the "directory" containing the *edited* item, the tooltip shows "`~/UK/GTS/Software/cfg/hftz - Contains emphasized items`" and by hovering over the the edited item itself, I get "`~/UK/GTS/Software/cfg/hftz/alpha_repo_allocator.ini - Edit`. ")

**Expected behavior:**
Both the original edited file and the shelved version should appear together beneath the changelist item.

Here is what I expect (and used to) see:

```
V  #4: The changelist description
  = alpha_repo_allocator.ini           [SE]           (NOTE: this item is a shelved file and appears grayed)
  = alpha_repo_allocator.ini            [E]           (NOTE: this item is the edited file)
```

**To Reproduce:**
I am running VSCode on a WIdows 10 machine with the Remote-SSH extension, and the all files in the workspace are located on the remote Linux machine,

It was working perfectly (i.e., as expected) for quite some time, but then it started doing this; I'm not entirely sure when it started happening, so I don't know how to reproduce it.

**Versions & Details:**
 - Perforce extension: v4.15.7
 - VSCode version: 1.77.3
 - Operating System: Windows 10 (VSCode), CentOS8 (remote server)
 - Perforce server details (if known): 
 - Are you using a multi-root workspace?: No

**Additional context**

Presumably the mjcrouch-perforce extension caches state somewhere. 

And further, presumably the extension must've gotten bollixed up (before the p4 refresh problem caused by the VSCode update to 1.76 was fixed in perforce-mjcrouch v4.15.7) and this messed-up state is somehow being propagated forward across invocations in the cached state info. 

I am hoping the solution might be as simple as deleting the cached state and restarting VSCode in the same workspace.

I just don't know where to look or what to delete.

<details>

```
Please open view -> Output, select "Perforce Log" from the dropdown and paste it here, if possible / relevant
```
Performing one-time registration of perforce commands
==============================
Workspace folders changed. Starting initialisation.

Workspaces were added
> file:///home/dm126569/UK/GTS/Software/src/hrel-47.0: Trying to initialise SCM Providers in this workspace.
	Note: the following overrides apply in this workspace:
		perforce.port: none	(will not override)
		perforce.user: none	(will not override)
		perforce.client: none	(will not override)
		perforce.dir: none	(will not override)
	Explicit overrides may prevent auto-detection of other perforce client workspaces
Looking for a client root using the workspace root directory
/home/dm126569/UK/GTS/Software/src/hrel-47.0: p4 'info'
> file:///home/dm126569/UK/GTS/Software/src/hrel-47.0: Found workspace using root directory
  * VS Code workspace root directory :
	Client name: dm126659_tbhftdev-d1
	Client root: /home/dm126569
	User name: dm126569
	Server address: usperforce-vp1:5500
	Folder IS in or above client root
> file:///home/dm126569/UK/GTS/Software/src/hrel-47.0: Looking for perforce config files
/home/dm126569/DD/BGC2/BGCMessaging/CPP/.vscode: p4 'info'
	>>> c_cpp_properties.json : Creating SCM provider for dm126659_tbhftdev-d1 @ /home/dm126569 because of source /home/dm126569/DD/BGC2/BGCMessaging/CPP/.vscode/c_cpp_properties.json
/home/dm126569/UK/GTS/Software/src/hrel-47.0: p4 'set' '-q'
> file:///home/dm126569/UK/GTS/Software/src/hrel-47.0: Using pattern **/.p4config
/home/dm126569/DD/BGC2/TradeEnricher/.vscode: p4 'info'
/home/dm126569/DD/BGC2/BGCMessaging/CPP/.vscode: p4 'login' '-s'
/home/dm126569/DD/BGC2/TradeEnricher/.vscode: p4 'info'
/home/dm126569/DD/BGC2/BGCMessaging/CPP/.vscode: p4 'login' '-s'
/home/dm126569/UK/GTS/Software/src/hrel-47.0/gts2: p4 'have' '/home/dm126569/UK/GTS/Software/src/hrel-47.0/gts2/ra_trade_utils.cpp'
/home/dm126569/UK/GTS/Software/src/hrel-47.0/tapi: p4 'have' '/home/dm126569/UK/GTS/Software/src/hrel-47.0/tapi/market_data_reader_eapi.cpp'
> file:///home/dm126569/UK/GTS/Software/src/hrel-47.0: Found 0 config file(s)
> file:///home/dm126569/UK/GTS/Software/src/hrel-47.0: Finding client roots using each file's directory
> file:///home/dm126569/UK/GTS/Software/src/hrel-47.0: Found the following roots from the location of 0 P4CONFIG file(s):

> file:///home/dm126569/UK/GTS/Software/src/hrel-47.0: SCM provider already exists for dm126659_tbhftdev-d1 @ /home/dm126569 - not creating another for source : /home/dm126569/UK/GTS/Software/src/hrel-47.0
> file:///home/dm126569/UK/GTS/Software/src/hrel-47.0: Initialisation done for this workspace. Created 0 provider(s), ignored 1 duplicate(s)

> file:///home/dm126569/DD/BGC2/Common/47.2: Trying to initialise SCM Providers in this workspace.
	Note: the following overrides apply in this workspace:
		perforce.port: none	(will not override)
		perforce.user: none	(will not override)
		perforce.client: none	(will not override)
		perforce.dir: none	(will not override)
	Explicit overrides may prevent auto-detection of other perforce client workspaces
Looking for a client root using the workspace root directory
/home/dm126569/DD/BGC2/BGCMessaging/CPP/.vscode: p4 'changes' '-l' '-c' 'dm126659_tbhftdev-d1' '-s' 'pending'
/home/dm126569/UK/GTS/Software/src/hrel-47.0/gts2: p4 'opened' '/home/dm126569/UK/GTS/Software/src/hrel-47.0/gts2/ra_trade_utils.cpp'
/home/dm126569/DD/BGC2/Common/47.2: p4 'info'
> file:///home/dm126569/DD/BGC2/Common/47.2: Found workspace using root directory
  * VS Code workspace root directory :
	Client name: dm126659_tbhftdev-d1
	Client root: /home/dm126569
	User name: dm126569
	Server address: usperforce-vp1:5500
	Folder IS in or above client root
> file:///home/dm126569/DD/BGC2/Common/47.2: Looking for perforce config files
/home/dm126569/UK/GTS/Software/src/hrel-47.0/gts2: p4 'print' '-q' '/home/dm126569/UK/GTS/Software/src/hrel-47.0/gts2/ra_trade_utils.cpp#have'
/home/dm126569/DD/BGC2/BGCMessaging/CPP/.vscode: p4 'describe' '-S' '-s' '4387368' '4387361' '4387338' '4387139' '4387014' '4386917' '4385567' '4384047' '4383488' '4381442' '4380546'
/home/dm126569/DD/BGC2/BGCMessaging/CPP/.vscode: p4 'opened'
/home/dm126569/UK/GTS/Software/src/hrel-47.0/tapi: p4 'print' '-q' '/home/dm126569/UK/GTS/Software/src/hrel-47.0/tapi/market_data_reader_eapi.cpp#have'
/home/dm126569/DD/BGC2/Common/47.2: p4 'set' '-q'
> file:///home/dm126569/DD/BGC2/Common/47.2: Using pattern **/.p4config
/home/dm126569/DD/BGC2/BGCMessaging/CPP/.vscode: p4 'fstat' '-e' '4387338' '-Or' '-Rs' '//UKDevelopment/GTS/Software/cfg/hftz/alpha_repo_allocator.ini'
/home/dm126569/DD/BGC2/BGCMessaging/CPP/.vscode: p4 'fstat' '-e' '4387139' '-Or' '-Rs' '//UKDevelopment/GTS/Software/src/hrel-47.0/gts2/makefile' '//UKDevelopment/GTS/Software/src/hrel-47.0/gts2/ra_eapi_subscriber.h' '//UKDevelopment/GTS/Software/src/hrel-47.0/gts2/ra_subscriber.h' '//UKDevelopment/GTS/Software/src/hrel-47.0/gts2/ra_trade_utils.cpp' '//UKDevelopment/GTS/Software/src/hrel-47.0/gts2/ra_trade_utils.h' '//UKDevelopment/GTS/Software/src/hrel-47.0/gts2/repo_allocator.cpp' '//UKDevelopment/GTS/Software/src/hrel-47.0/gts2/repo_allocator.h'
/home/dm126569/DD/BGC2/BGCMessaging/CPP/.vscode: p4 'fstat' '-e' '4387014' '-Or' '-Rs' '//UKDevelopment/GTS/Software/src/hrel-47.0.25/gts2/load_repo_data_funcs.cpp' '//UKDevelopment/GTS/Software/src/hrel-47.0.25/gts2/load_repo_data_funcs.h' '//UKDevelopment/GTS/Software/src/hrel-47.0.25/test/setup-gmem.cpp'
/home/dm126569/DD/BGC2/BGCMessaging/CPP/.vscode: p4 'fstat' '-e' '4386917' '-Or' '-Rs' '//UKDevelopment/GTS/Software/src/hrel-47.0/test/setup-gmem.cpp' '//UKDevelopment/GTS/Software/src/hrel-47.0/test/test-load_repo_data_funcs.cpp'
/home/dm126569/DD/BGC2/BGCMessaging/CPP/.vscode: p4 'fstat' '-e' '4385567' '-Or' '-Rs' '//DistributedDevelopment/BGC2/BGCMessaging/CPP/MessagingAPI/impl/message.cpp'
/home/dm126569/DD/BGC2/BGCMessaging/CPP/.vscode: p4 'fstat' '-e' '4384047' '-Or' '-Rs' '//DistributedDevelopment/BGC2/BGCMessaging/CPP/SampleClients/SnapshotSub.cpp'
/home/dm126569/DD/BGC2/BGCMessaging/CPP/.vscode: p4 'fstat' '-e' '4380546' '-Or' '-Rs' '//UKDevelopment/GTS/Software/cfg/gts2/hft_master.cfg' '//UKDevelopment/GTS/Software/cfg/hftg/devus_bgc2_publisher.ini' '//UKDevelopment/GTS/Software/cfg/hftg/devus_collateral_data.ini' '//UKDevelopment/GTS/Software/cfg/hftg/devus_market_data_reader_eapi.ini' '//UKDevelopment/GTS/Software/cfg/hftg/devus_repo_allocator.ini' '//UKDevelopment/GTS/Software/cfg/hftz/alpha_repo_allocator.ini'
/home/dm126569/DD/BGC2/BGCMessaging/CPP/.vscode: p4 'fstat' '-Or' '//DistributedDevelopment/BGC2/BGCMessaging/CPP/MessagingAPI/impl/message.cpp' '//DistributedDevelopment/BGC2/ME/47.2/test_utils/LimitTrade.cpp' '//DistributedDevelopment/BGC2/ME/47.2/test_utils/MktdSub.cpp' '//UKDevelopment/GTS/Software/cfg/hftg/devus_bgc2_publisher.ini' '//UKDevelopment/GTS/Software/cfg/hftg/devus_collateral_data.ini' '//UKDevelopment/GTS/Software/cfg/hftg/devus_inst_creator.ini' '//UKDevelopment/GTS/Software/cfg/hftg/devus_market_data_reader_eapi.ini' '//UKDevelopment/GTS/Software/cfg/hftg/devus_repo_allocator.ini' '//UKDevelopment/GTS/Software/cfg/hftz/alpha_repo_allocator.ini' '//UKDevelopment/GTS/Software/src/hrel-47.0/gts2/makefile' '//UKDevelopment/GTS/Software/src/hrel-47.0/gts2/ra_eapi_subscriber.h' '//UKDevelopment/GTS/Software/src/hrel-47.0/gts2/ra_subscriber.h' '//UKDevelopment/GTS/Software/src/hrel-47.0/gts2/ra_trade_utils.cpp' '//UKDevelopment/GTS/Software/src/hrel-47.0/gts2/ra_trade_utils.h' '//UKDevelopment/GTS/Software/src/hrel-47.0/gts2/repo_allocator.cpp' '//UKDevelopment/GTS/Software/src/hrel-47.0/gts2/repo_allocator.h'
> file:///home/dm126569/DD/BGC2/Common/47.2: Found 0 config file(s)
> file:///home/dm126569/DD/BGC2/Common/47.2: Finding client roots using each file's directory
> file:///home/dm126569/DD/BGC2/Common/47.2: Found the following roots from the location of 0 P4CONFIG file(s):

> file:///home/dm126569/DD/BGC2/Common/47.2: SCM provider already exists for dm126659_tbhftdev-d1 @ /home/dm126569 - not creating another for source : /home/dm126569/DD/BGC2/Common/47.2
> file:///home/dm126569/DD/BGC2/Common/47.2: Initialisation done for this workspace. Created 0 provider(s), ignored 1 duplicate(s)

> file:///home/dm126569/DD/BGC2/BGCMessaging/CPP: Trying to initialise SCM Providers in this workspace.
	Note: the following overrides apply in this workspace:
		perforce.port: none	(will not override)
		perforce.user: none	(will not override)
		perforce.client: none	(will not override)
		perforce.dir: none	(will not override)
	Explicit overrides may prevent auto-detection of other perforce client workspaces
Looking for a client root using the workspace root directory
/home/dm126569/DD/BGC2/BGCMessaging/CPP: p4 'info'
> file:///home/dm126569/DD/BGC2/BGCMessaging/CPP: Found workspace using root directory
  * VS Code workspace root directory :
	Client name: dm126659_tbhftdev-d1
	Client root: /home/dm126569
	User name: dm126569
	Server address: usperforce-vp1:5500
	Folder IS in or above client root
> file:///home/dm126569/DD/BGC2/BGCMessaging/CPP: Looking for perforce config files
/home/dm126569/DD/BGC2/BGCMessaging/CPP: p4 'set' '-q'
> file:///home/dm126569/DD/BGC2/BGCMessaging/CPP: Using pattern **/.p4config
> file:///home/dm126569/DD/BGC2/BGCMessaging/CPP: Found 0 config file(s)
> file:///home/dm126569/DD/BGC2/BGCMessaging/CPP: Finding client roots using each file's directory
> file:///home/dm126569/DD/BGC2/BGCMessaging/CPP: Found the following roots from the location of 0 P4CONFIG file(s):

> file:///home/dm126569/DD/BGC2/BGCMessaging/CPP: SCM provider already exists for dm126659_tbhftdev-d1 @ /home/dm126569 - not creating another for source : /home/dm126569/DD/BGC2/BGCMessaging/CPP
> file:///home/dm126569/DD/BGC2/BGCMessaging/CPP: Initialisation done for this workspace. Created 0 provider(s), ignored 1 duplicate(s)

> file:///home/dm126569/DD/BGC2/TradeEnricher: Trying to initialise SCM Providers in this workspace.
	Note: the following overrides apply in this workspace:
		perforce.port: none	(will not override)
		perforce.user: none	(will not override)
		perforce.client: none	(will not override)
		perforce.dir: none	(will not override)
	Explicit overrides may prevent auto-detection of other perforce client workspaces
Looking for a client root using the workspace root directory
/home/dm126569/DD/BGC2/TradeEnricher: p4 'info'
> file:///home/dm126569/DD/BGC2/TradeEnricher: Found workspace using root directory
  * VS Code workspace root directory :
	Client name: dm126659_tbhftdev-d1
	Client root: /home/dm126569
	User name: dm126569
	Server address: usperforce-vp1:5500
	Folder IS in or above client root
> file:///home/dm126569/DD/BGC2/TradeEnricher: Looking for perforce config files
/home/dm126569/DD/BGC2/TradeEnricher: p4 'set' '-q'
> file:///home/dm126569/DD/BGC2/TradeEnricher: Using pattern **/.p4config
> file:///home/dm126569/DD/BGC2/TradeEnricher: Found 0 config file(s)
> file:///home/dm126569/DD/BGC2/TradeEnricher: Finding client roots using each file's directory
> file:///home/dm126569/DD/BGC2/TradeEnricher: Found the following roots from the location of 0 P4CONFIG file(s):

> file:///home/dm126569/DD/BGC2/TradeEnricher: SCM provider already exists for dm126659_tbhftdev-d1 @ /home/dm126569 - not creating another for source : /home/dm126569/DD/BGC2/TradeEnricher
> file:///home/dm126569/DD/BGC2/TradeEnricher: Initialisation done for this workspace. Created 0 provider(s), ignored 1 duplicate(s)

> file:///home/dm126569/UK/GTS/Software/com: Trying to initialise SCM Providers in this workspace.
	Note: the following overrides apply in this workspace:
		perforce.port: none	(will not override)
		perforce.user: none	(will not override)
		perforce.client: none	(will not override)
		perforce.dir: none	(will not override)
	Explicit overrides may prevent auto-detection of other perforce client workspaces
Looking for a client root using the workspace root directory
/home/dm126569/UK/GTS/Software/src/hrel-47.0/gts2: p4 'have' '/home/dm126569/UK/GTS/Software/src/hrel-47.0/gts2/ra_trade_utils.cpp'
/home/dm126569/UK/GTS/Software/src/hrel-47.0/tapi: p4 'have' '/home/dm126569/UK/GTS/Software/src/hrel-47.0/tapi/market_data_reader_eapi.cpp'
/home/dm126569/UK/GTS/Software/com: p4 'info'
> file:///home/dm126569/UK/GTS/Software/com: Found workspace using root directory
  * VS Code workspace root directory :
	Client name: dm126659_tbhftdev-d1
	Client root: /home/dm126569
	User name: dm126569
	Server address: usperforce-vp1:5500
	Folder IS in or above client root
> file:///home/dm126569/UK/GTS/Software/com: Looking for perforce config files
/home/dm126569/UK/GTS/Software/com: p4 'set' '-q'
> file:///home/dm126569/UK/GTS/Software/com: Using pattern **/.p4config
> file:///home/dm126569/UK/GTS/Software/com: Found 0 config file(s)
> file:///home/dm126569/UK/GTS/Software/com: Finding client roots using each file's directory
> file:///home/dm126569/UK/GTS/Software/com: Found the following roots from the location of 0 P4CONFIG file(s):

> file:///home/dm126569/UK/GTS/Software/com: SCM provider already exists for dm126659_tbhftdev-d1 @ /home/dm126569 - not creating another for source : /home/dm126569/UK/GTS/Software/com
> file:///home/dm126569/UK/GTS/Software/com: Initialisation done for this workspace. Created 0 provider(s), ignored 1 duplicate(s)

> file:///home/dm126569/UK/GTS/Software/cfg: Trying to initialise SCM Providers in this workspace.
	Note: the following overrides apply in this workspace:
		perforce.port: none	(will not override)
		perforce.user: none	(will not override)
		perforce.client: none	(will not override)
		perforce.dir: none	(will not override)
	Explicit overrides may prevent auto-detection of other perforce client workspaces
Looking for a client root using the workspace root directory
/home/dm126569/UK/GTS/Software/cfg: p4 'info'
> file:///home/dm126569/UK/GTS/Software/cfg: Found workspace using root directory
  * VS Code workspace root directory :
	Client name: dm126659_tbhftdev-d1
	Client root: /home/dm126569
	User name: dm126569
	Server address: usperforce-vp1:5500
	Folder IS in or above client root
> file:///home/dm126569/UK/GTS/Software/cfg: Looking for perforce config files
/home/dm126569/UK/GTS/Software/cfg: p4 'set' '-q'
> file:///home/dm126569/UK/GTS/Software/cfg: Using pattern **/.p4config
> file:///home/dm126569/UK/GTS/Software/cfg: Found 0 config file(s)
> file:///home/dm126569/UK/GTS/Software/cfg: Finding client roots using each file's directory
> file:///home/dm126569/UK/GTS/Software/cfg: Found the following roots from the location of 0 P4CONFIG file(s):

> file:///home/dm126569/UK/GTS/Software/cfg: SCM provider already exists for dm126659_tbhftdev-d1 @ /home/dm126569 - not creating another for source : /home/dm126569/UK/GTS/Software/cfg
> file:///home/dm126569/UK/GTS/Software/cfg: Initialisation done for this workspace. Created 0 provider(s), ignored 1 duplicate(s)

Initialisation finished
==============================

/: p4 'opened' 'extension-output-mjcrouch.perforce-%231-Perforce Log'

</details>

**Comment by mjcrouch** [comment]
Hi,

Not at my computer right now to check the exact details. 

vs code has two modes for displaying files in the SCM panel, either the default flat mode or the tree view that structures them by directory. I think you just need to click the button at the top of the SCM panel that looks like a file tree structure to toggle the mode back to the normal one.

Ideally we might want the tree structure to show them in the same place but it's not something I ever put much thought into!

(we don't store much in the way of state, tbh I can't remember off the top of my head if there's anything at-all that's persisted between sessions other than the vs code settings items)

**Comment by dmiller-bgc** [comment]
Aha! Thanks!  The list/tree mode toggle button! Never occurred to me there might be such a thing, let alone that I may have accidentally clicked it.
Sorry for bothering you with this nonsense.
Thanks again.
