### ISSUE TITLE
compare does not work

### ISSUE THREAD

**Issue by geromueller** [mjcrouch/vscode-perforce#38]
**Describe the bug:**
when comparing files the p4 command is missing and p4args are not quoted

**Expected behavior:**
working compare command

**To Reproduce:**
double click modified file

**Versions & Details:**
 - Perforce extension: 3.5.1
 - VSCode version: 1.41.1
 - Operating System: Win10 (Linux over SSH)
 - Perforce server details (if known):
 - Are you using a multi-root workspace?: No

**Additional context**

```
"/usr/local/bin/p4" -u geromuller -p perforce01:1666  p4args=-q&command=print&workspace=/home/geromuller/ws "home/geromuller/ws/makefile#2241"
ERROR: "Error: Command failed: \"/usr/local/bin/p4\" -u geromuller -p perforce01:1666  p4args=-q&command=print&workspace=/home/geromuller/ws\" /home/geromuller/ws/makefile#2241\"\n/bin/sh: /home/geromuller/ws/makefile#2241: No such file or directory\nUnknown command.  Try 'p4 help' for info.\n"

```

**Comment by geromueller** [comment]
nevermind, was a bug in the old extension

**Comment by mjcrouch** [comment]
Ah, did you have both of the extensions running?

this part: "p4args=-q&command=print&workspace=/home/geromuller/ws" can only come from my version of the extension, but I was stuck trying to understand how it got in to a perforce command as this is only used internally to pass details to the diff command

**Comment by geromueller** [comment]
yes... 🙄
