### ISSUE TITLE
Investigate P4IGNORE issues

### ISSUE THREAD

**Issue by mjcrouch** [mjcrouch/vscode-perforce#5]
[P4IGNORE spec](https://www.perforce.com/manuals/v15.2/cmdref/P4IGNORE.html)

An outdated version of the parse-gitignore npm package is used - which supports turning lines from a gitignore file in to a glob pattern. The new version (v1.0.0+) has substantially reduced functionality - i.e. it does not turn lines in to usable glob patterns. In order to get the dependencies up to date a new method should be used.

Additionally there are a couple of issues with the existing code 

1) Only reads file on open - if the p4ignore file is changed after the extension has initialised, the extension will not reflect those updates.
2) The P4IGNORE env variable can specify many files - but the extension always assumes it is one file
3) A p4ignore file may be specified as an absolute path, but the extension only reads p4ignore files relative to the workspace root
4) A p4ignore path may contain environment variables like $home/.p4ignore, but these are not expanded
5) It only appears to apply the p4ignore settings to delete operations, and not to add / edit operations

The p4ignore spec makes special mention of the `\` character for windows, while the gitignore spec does not - need to investigate this one.

On further testing it doesn't seem to work with the old parse-gitignore version either.

- I added a gitignore file containing the line `ignoreMe/**` and a file in the ignoreMe directory within the workspace.
- Manually running p4 add, it refuses to add the file due to being ignored.
- However, if I delete the file from the filesystem, the extenssion still tries to p4 delete it because it matches `ignoreMe/**` against the URI of the file, instead of `**/ignoreMe/**`

This area seems to need a lot of work, but it is not that significant as a priority because it largely doesn't cause observable issues.

**Comment by mjcrouch** [comment]
Not a very easy task...

Some investigation in to how p4ignore actually works, via trial and error (because most of this is not documented)

* If an absolute path like $home/.p4ignore is supplied in the P4IGNORE setting, that file's patterns match against any path
* If a relative path like .p4ignore is supplied, patterns only apply to files at or below the level of that file
* If file `a/.p4ignore` specifies a pattern, `a/b/.p4ignore` can negate that pattern
* If `a/b/.p4ignore` specifies a pattern, `a/.p4ignore` cannot negate that pattern
* Not sure how the order of absolute vs relative files in the .p4ignore affects negation

This means that we need to discover all of the files for a given workspace, then we can turn them into an overall list of glob patterns - highest directory first, using absolute paths at the start of the pattern for each .p4ignore file's paths

I did look at using p4 ignores to provide the list of patterns, but it doesn't correctly output the patterns for absolute .p4ignore files (it only shows patterns relative to that file, but actually applies them to any matching path in the workspace)

**Comment by allender** [comment]
p4ignore is only used for adds and reconciling offline work.  The top of the docs state:

> Specify a list of files that contain lists of rules for ignoring files when adding files to the depot and reconciling workspaces.

I'm not sure what specific issues there are with respect to p4ignore, but it's not clear to me that there is anything really that needs to be done.  I looked at the [original bug](https://github.com/stef-levesque/vscode-perforce/issues/27) filed in the original depot.  I'm not entirely sure that this is a p4ignore issue at all actually.  The plugin shouldn't need to look at this file for deletion or anything else.  If the file is already in the depot you act on it as normal (as you have seen).  If it's not, you p4 add and it will either add or not depending on the p4ignore value.  If you are adding through vscode you should be able to report a message back to the user if the file is p4ignored.

**Comment by mjcrouch** [comment]
yes I did see that original issue, the main justification originally seemed to be preventing the log output from being filled up, I couldn't see any specific complaints about resource usage etc.

The issues it currently faces are it is pretty much useless at matching most patterns specified in the log file beyond very basic ones, it doesn't respect the hierarchy of p4ignore files, and it doesn't even check it on 'add' anyway, only on delete.

I _can_ see an argument for not issuing a whole load of perforce commands (which means spawning subprocesses) when something like node_modules is updated, as you're never going to be interested in those files. 

While technically, the delete operation shouldn't be ignored, because it may be a valid operation, equally it's very unlikely in the case of a folder like node_modules that someone would have added them in the first place. For a delete, we could probably do some debouncing to stack these in to a single command anyway - (incidentally this might also resolve that issue with files being opened for delete when edited externally)

However, vscode does provide an "Ignore" setting which is also already used in combination with the current p4 ignore config.

Overall I think I agree, the p4ignore handling should just be removed, and we should just consider files in the generic ignore setting to not be valid for any *automatic* actions

I have noticed that the extension often reports "File opened for add" even if an error was returned, so probably need to fix that.

**Comment by allender** [comment]
yes, I personally think that p4ignore handling should be removed altogether.  Plugin should be reporting proper information back to user in the log.  (by generic ignore setting you mean the plugin setting yes?).   With some thought, delete handling could be modified to handle the various cases (log, less server spam, not running p4 delete on files that have been deleted, etc).  I forked the repo and might start to think about the delete actions and how to deal with them (if you're willing to accept pull requests).  Removal of p4ignore handling would be a part of that.

**Comment by mjcrouch** [comment]
IIRC the generic ignore I was referring to was the VS code settings "File: Exclude" - though I haven't done much investigation there. May be "watcher exclude" is enough as it will probably prevent them getting picked up anyway

> if you're willing to accept pull requests

Of course :) FYI I'm slowly trying to refactor specific command lines and parsing out of all the different areas and replace them with the more unified PerforceApi.ts module, which may affect this area slightly. General feedback of command results is something that needs a bit of work as well in some cases
