### ISSUE TITLE
P4 set doesn't work in some environments, affecting perforce client detection

### ISSUE THREAD

**Issue by mjcrouch** [mjcrouch/vscode-perforce#53]
p4 set is used to get the P4CONFIG variable if it exists

In some environments, `p4 set -q` returns an error:

```
Perforce client error:
        p4 -h for usage.
        Invalid option: -q.
```

(despite being documented as a valid option in the help)

This means that in some instances where we would be able to pick up a valid p4 client using a p4 config, we are unable to

This is really a bug in perforce, but could be handled in the extension

Seen in: Rev. P4/LINUX26X86_64/2014.1/821990 (2014/04/08).

**Comment by allender** [comment]
This probably isn’t a perforce big. Plugin uses command line client at least in this case. The original problem probably comes from someone with older command line client where -q option was not available. I can check release notes to find out when it was added. Plugin needs to handle but we could also require specific command line client version too.

**Comment by mjcrouch** [comment]
I am that someone! :D

if I run p4 help set it shows the -q option , but it doesn't work. version is shown above. It's not affecting me but I don't have the option to upgrade perforce in a corporate environment.

 Not a high priority though

**Comment by allender** [comment]
It should be easy enough to fix the parsing code to not use -q

**Comment by mjcrouch** [comment]
closing this anyway.. managed to upgrade my version. Being quite a few years old, doesn't seem worth the effort / risk of changing the parsing code
