### ISSUE TITLE
New delete on file delete handling doesn't handle deleted directories

### ISSUE THREAD

**Issue by mjcrouch** [mjcrouch/vscode-perforce#60]
**Describe the bug:**
When a directory is deleted from the explorer, vscode passes us a **directory** instead of a specific file in that directory. This is good because it avoids having an event for every single file (e.g. if you delete the node_modules directory), but PerforceCommands tries to revert / delete the directory, without any wildcard specifiers

**Expected behavior:**
Ideally should revert and delete the file using the wildcard specifier, e.g. `C:\\mydepot\\deletedDir\\...` seems to work - I guess we'll need to make a new URI with the dots on the end, using `uri.with`, but may need some thought (I'll take a look if I get a chance, but maybe not until monday) - if I'm right, it looks like vscode doesn't explicitly tell us it's a directory, so we may need to use `onWillDeleteFiles` and work it out for ourselves - but then we may need to get into using `waitUntil` if it's an async call to determine a directory, which is not ideal
Alternatively may want to raise a PR in vscode if there's a simple way to change it to make it tell us that it's a directory (don't think there is a sensible way, because the interface is a list of Uris)

The best option if there's no other way, is probably use `onWillDeleteFiles` - then call `waitUntil` - ensure the promise resolves **as soon as** the directory check is done, then kick off the revert / delete on that without awaiting the result. A synchronous check is technically possible but not sure if it's a good idea.

**To Reproduce:**
1. Enable delete on file delete setting
2. Create a directory, add files / folders to it and add them to perforce
2. Delete the directory
3. Perforce reports the file is not open

**Versions & Details:**
 - Perforce extension: (**master - not released yet**)

**Additional context**

<details>

```
c:/Users/zogge/Perforce/default/: C:\\Program Files\\Perforce\\p4.exe '-c' 'default' 'revert' 'c:\Users\zogge\Perforce\default\testFolder'
ERROR: "c:\\Users\\zogge\\Perforce\\default\\testFolder - file(s) not opened on this client.\r\n"
c:/Users/zogge/Perforce/default/: C:\\Program Files\\Perforce\\p4.exe '-c' 'default' 'delete' 'c:\Users\zogge\Perforce\default\testFolder'
ERROR: "c:\\Users\\zogge\\Perforce\\default\\testFolder - file(s) not on client.\r\n"
```

</details>

**Comment by allender** [comment]
Ah. Shoot. Yes. We can use the directory wildcard even on local path. I’m happy to fix this although will probably be Monday am (CDT) before I can get to it.

**Comment by mjcrouch** [comment]
Looks like the fileWillDeleteEvent gives us one event per file, so my suggested approach is probably nonsense.

Another idea, perhaps a little complicated but involves no async calls:
* cache the set of `onWilDeleteFiles` events, 
* when we get the `onDidDeleteFiles` event, check the cache to see if any of them are within the path provided to us in the didDelete event.
* I guess clear the cache as we receive applicable `didDelete` events

**Comment by mjcrouch** [comment]
had some unexpected free time tonight so implemented something that seems to work ok

**Comment by allender** [comment]
Thanks. Was going to look at this later tonight. Appreciate the assist

----
-Mark
