### ISSUE TITLE
Fix handling of files outside of the workspace

### ISSUE THREAD

**Issue by jan11011977** [mjcrouch/vscode-perforce#73]
**Describe the bug:**
When opening a file that is in a different Perforce workspace than the one opened in Visual Studio Code, the Perforce plugin tries to connect to the wrong Perforce server.

**Expected behavior:**
'Edit' command works on all files, regardless of whether they are in the VSCode opened folder or not.

**To Reproduce:**
- Open a folder in VSCode
- Open a file in VSCode that lives in Perforce, but in a different workspace from the folder you opened in VSCode
- Attempt to run any command e.g. Edit

**Additional context**
The reason this is going wrong, is that the Perforce plugin is running the commands with the wrong working directory. For example if you were to open the c:\example directory in VSCode, all commands will run with that as the current working directory. So if I then opened a file in VSCode called c:\example2\test.txt, and did "Edit", it would run that command with c:\example as the current working directory.
Perforce will then look for the .p4config file in c:\example instead of c:\example2, and it will find the wrong .p4config file.
The fix is quite straightforward. In fact I have an example fix for you in a fork I made here:

https://github.com/jan11011977/vscode-perforce/commit/b6af49b354c4cae5382759215797686c37d6ff6b

(see also the subsequent checkin)

**Comment by mjcrouch** [comment]
Thanks for the issue - I had noticed your fork on the network graph - Have you tried this in my version, I [recently made an update](https://github.com/mjcrouch/vscode-perforce/commit/30e5c65620c1ce0de4e99833639ece9c8b4cc756#diff-f03adad7836adb1538341c44b4eaeaa0L243) to run all commands in the file's directory if it's not in a workspace? It seemed to generally work for me

**Comment by mjcrouch** [comment]
Going to close this for now as I believe it is already resolved, but please reply back on this issue if you are still having problems with it
