### ISSUE TITLE
Submit selected files fails on Windows

### ISSUE THREAD

**Issue by maciejmatczak** [mjcrouch/vscode-perforce#74]
**Describe the bug:**
Files are not uploaded when using "Submit selected files...", error is printed:
```text
c:/[...]/: p4.exe 'change' '-o'
c:/[...]/: p4.exe 'change' '-i'
ERROR: "Error in change specification.\r\nError detected at line 13.\r\nSyntax error in '\t '.\r\n"
```

**Expected behavior:**
Files got uploaded.

**To Reproduce:**
Edit one/couple of files. While those are on the default changelist, select them, "Submit selected files...", provide the change descriptions, upload fails.

**Versions & Details:**
 - Perforce extension: 3.8.0 - 2020-03-13
 - VSCode version: 1.43.0
 - Operating System: Windows 10
 - Perforce server details (if known): 
 - Are you using a multi-root workspace?: No

**Additional context**

Are we somehow able to more verbosely printed what input went into `p4 change -i`?

**Comment by mjcrouch** [comment]
Thanks - is saving a changelist (just enter a description and press ctrl + enter), or updating a changelist description working ok?

It works for me on windows but it looks like there may be some difference in the way it's interpreting the tab character for you..

Don't have a way to print out the input atm - but probably worth adding - general verbosity options is something I would like to add as well

**Comment by maciejmatczak** [comment]
The same issue on saving the changelist...

Can I help anyhow from my side, test anything? I'll try to recreate how the plugin creates the the change spec...

@mjcrouch, that was fast! Thanks :)

**Comment by mjcrouch** [comment]
It runs p4 change -o to get the list of all the fields in the changespec.
For each field it parses them, stripping off any leading tabs and any multiline fields turn into an array of one string per line.

Then it inputs the change using the same set of fields it just parsed, with any changed fields if appropriate (in this case, the description)

For every field it uses the field name, followed by a colon, followed by the tab character, followed by the field value. If the field value is multiple lines, it joins the lines together with "\n\t".
It then joins all the fields together with "\n"

like this:
```
...
.map(field => field.name + ":\t" + field.value.join("\n\t"))
                .join("\n\n")
```

Perhaps it's picking up something else from your changespec that I don't have. 

These things would probably be relevant
* The output of p4 change -o (including the whitespace - I think it's the same as running p4 change and then copying what's in the editor, which is easier than copying the correct whitespace out of a terminal in windows in my experience)
* The output of p4 info - for the server version field (not sure if the server version is actually involved)
* The output of p4 -V for the client version

**Comment by mjcrouch** [comment]
I've pushed a new version which logs the command input - should make it more obvious where the problem is :)

**Comment by maciejmatczak** [comment]
```text
# A Perforce Change Specification.
#
#  Change:      The change number. 'new' on a new changelist.
#  Date:        The date this specification was last modified.
#  Client:      The client on which the changelist was created.  Read-only.
#  User:        The user who created the changelist.
#  Status:      Either 'pending' or 'submitted'. Read-only.
#  Type:        Either 'public' or 'restricted'. Default is 'public'.
#  Description: Comments about the changelist.  Required.
#  ImportedBy:  The user who fetched or pushed this change to this server.
#  Identity:    Identifier for this change.
#  Jobs:        What opened jobs are to be closed by this changelist.
#               You may delete jobs from this list.  (New changelists only.)
#  Files:       What opened files from the default changelist are to be added
#               to this changelist.  You may delete files from this list.
#               (New changelists only.)

Change:	new

Client:	client_name

User:	username

Status:	new

Description:
	<enter description here>

Jobs: 

Files:
	//file_path	# edit
	//file_path2	# edit

```

I have additionally "Jobs" field in a changelist template, thing is that after plugin parsing, it gets changed from:
`Jobs: ` (only one space)
to:
`Jobs:\t ` (tab and a space)

Maybe additional check if/else value of the field is empty?

Thanks for help!

**Comment by mjcrouch** [comment]
thanks - looking at fixing it now - I can test that it produces the right value for the input, but I can't actually reproduce the parsing error from perforce if I manually input a change spec with a tab and a space. Perforce just accepts it whatever whitespace I put in.

If you manually input a change spec with the job field having a tab but NO space - does that still result in an error from perforce? Or if you input a change spec with the job field having no whitespace at-all before the new-line?

As the change input part is relatively generic, I'm trying to make sure it's doing the "right thing" with an empty field - for example if you want to remove all the job fixes, you can supply an empty value. So I don't want to skip the field completely if we ever need to do something like that.

**Comment by maciejmatczak** [comment]
Did a couple of testing more. It seems like two new lines on the end gets things done. Try leaving any empty field without new lines after it as the last statement.

<details>
<summary>Error case</summary>

```text
# Gives an error:
# Error in change specification.
# Error detected at line 18.
# Syntax error in '        '.

Change:	new

Description:	test 

Files:	filepath	# edit

Client:	clientname

User:	username

Status:	new

Jobs:	 
```

</details>
<details>
<summary>Job field in the middle - success</summary>

```text
# Successfully creates changelist
# 
# I just moved "Jobs\t " to the middle of the spec

Change:	new

Description:	test 

Files:	filepath	# edit

Client:	clientname

User:	username

Jobs:	 

Status:	new
```

</details>
<details>
<summary>2 new lines on the end - success</summary>

```text
# Successfully creates changelist
# 
# Aded two new lines on the end

Change:	new

Description:	test 

Files:	file	# edit

Client:	clientname

User:	username

Status:	new

Jobs:	 


```

</details>

**Comment by maciejmatczak** [comment]
@mjcrouch, BTW, for scripting in P4 you might be interested in:
https://community.perforce.com/s/article/15148

**Comment by mjcrouch** [comment]
thanks, I wasn't aware of that - I knew of ztag and found it seems to be harder to parse in some cases, but this could be useful to simplify some of the parsing

**Comment by mjcrouch** [comment]
published - hopefully it works

**Comment by maciejmatczak** [comment]
@mjcrouch, works great, thanks!
