### ISSUE TITLE
ssh remote not working

### ISSUE THREAD

**Issue by maciejmatczak** [mjcrouch/vscode-perforce#80]
**Describe the bug:**
After setting up the ssh remote session, perforce do not initialize. Trying to use any of the perforce commands shows popup with `command 'perforce.login' not found`.

Extension is installed on the remote target.

**Expected behavior:**
Everything working fine :)

**To Reproduce:**
SSH remote to the host, install `vscode-perforce` extension, try using it.

**Versions & Details:**
 - Perforce extension: 3.10.0
 - VSCode version: 1.43.2
 - Operating System: Windows host, CentOS 7.3 on remote
 - Perforce server details (if known):
 - Are you using a multi-root workspace?: No

**Comment by mjcrouch** [comment]
Hi,

I don't believe this would be specific to remote SSH - I'm using the extension mainly in remote SSH - it may depend on how you've configured perforce. e.g. whether you use environment variables, p4 configs etc to determine which client to use, or the extension's own config

Can you check if the Output log for perforce has any details? It should give some clues.

Thanks,
Matt

**Comment by maciejmatczak** [comment]
Hi @mjcrouch, 

My bad, extension output was the first thing I tried to check, but I didn't see any, it did not exist at all (after installation and "Reload required"). But now, after manual reload, I can actually see it properly shown. Config issue was on my side, log helped.

Thanks and sorry to bother!
