### ISSUE TITLE
Reshelve option for files

### ISSUE THREAD

**Issue by unwiredben** [mjcrouch/vscode-perforce#92]
We use Swarm for code reviews, and that often involved shelving a set of files, getting review notes, then reshelving the files to update.  The current shelf interface assumes that you want to unshelve files if they're already shelved instead of updating an existing shelf.

I'd like to see a new context menu option that would 'p4 reshelve' a changelist, updating the files in the shelf to match the workspace.

**Comment by mjcrouch** [comment]
Hi - thanks for the suggestion

If you right click on the changelist and choose "shelve changelist" this uses the `-f` option, which is close to `-r` - except it doesn't delete shelved files that you've removed from your changelist -  if you have removed any you can right click on the shelved files and choose delete shelved file

We have a similar workflow and we also use shelves to share code before review, so this was the very first thing I added; the whole reason the fork exists :)

We could consider adding reshelve as well, which could be switched based on whether there are any shelved files in the changelist already

I also created issue #91 today about the general behaviour when shelving individual files which is related to this

**Comment by unwiredben** [comment]
OK, reshelve isn't what I wanted.  I think you already handle the case, I just got confused by the individual file shelve/unshelve behavior, especially when I have shelved files hidden.
