### ISSUE TITLE
Error while diffing previous from working

### ISSUE THREAD

**Issue by makail** [mjcrouch/vscode-perforce#97]
`ERROR: "//depot/somefile.txt" - must refer to client 'perforce_client'.`

The error here is caused by using a depot path instead of the client path for the p4 print command. Possibly only in my perforce setup using a mapped view of a stream.

I fixed it locally by modifying DiffProvider.ts (there's probably a better way to do this?):

```
async function diffPreviousFromWorking(fromDoc: Uri) {
    const revision = (await p4.have(fromDoc, { file: fromDoc }))?.revision;
    if (!revision) {
        Display.showImportantError("No previous revision available");
        return;
    }
    const args = { haveRev: revision };
    await diffFiles(
        PerforceUri.fromUri(fromDoc, args),
        PerforceUri.withArgs(fromDoc, args)
    );
}
```

**Comment by mjcrouch** [comment]
Thanks - hmm, I haven't really used streams but I just created a stream depot and a stream and didn't have any problems using a depot path for p4 print. Could you give more detail on the specific setup? I'm not sure exactly what the case is where using the depot path is an error

* is the depot path it uses the right depot path for the file?
* is it running the command from the right directory (in the output log, the start of the line is the working directory)

I think just changing to the local file *might* have some impact on some other features such as the quick pick that was recently added

**Comment by allender** [comment]
I am not aware of any stream features that would cause using p4 print from command line to _not_ work with depot syntax.  The only rules that p4 print is typically subject to is the protections table.  This _could_ be a version issue with the server, but if you look at the current docs for p4 print, it states:  "If the file argument does not map through the client view, you must provide it in depot syntax." which implies that it doesn't have to map through client view at all, so this error seems misleading in some way  re you sure the error is coming from the 'p4 print' command

**Comment by makail** [comment]
I'm sure it is, I can run the command (p4 print) directly using the depot path (which is correct) and it returns the same error. I have a stream, with a virtual stream off it that explicitly shares various paths from the parent stream.

ex:
`share engine/src/...`
where `engine/src` is a path existing in the parent stream. 

The `p4 have` command resolves the client path to the correct depot path, but I believe the mapping prevents it from resolving in the opposite direction.

**Comment by allender** [comment]
seems like a perforce bug.  p4 print doesn't resolve through client specs.  it only uses the protection table (which is what makes this error so bizarre)

**Comment by makail** [comment]
It is worth noting that `diffDefault` (used by the SCM tree view) uses a client path as the left file.

**Comment by makail** [comment]
Went over what I found yesterday to verify. Looking more closely at the paths, it's purely the casing is incorrect. Nothing to do with the mapping at all, thankfully. For some reason the authority sent to the ContentProvider is lower cased.

**Comment by mjcrouch** [comment]
ah ok, interesting... this could be a limitation of using vscode Uris to represent depot paths, given that a depot path isn't really a Uri. If that's the case then we should probably encode the original 'authority' 

I have pushed a branch with something very close to your change and will probably publish that shortly - I don't think there's any problem using a local path for now, then can look at what we can do to fix handling of depot paths like that

**Comment by makail** [comment]
Cool cool. Looks like https://tools.ietf.org/html/rfc3986#section-6.2.2.1 may be why the uri is lower-cased, and confirms your conclusion.

**Comment by mjcrouch** [comment]
well, I reproduced it and it was only two functions to get the case right - should be published in a couple of minutes
